server:
  address: 127.0.0.2
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QianNvYouHun
    url: jdbc:mysql://localhost:3306/zay_musicwebdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

mybatis:
  type-aliases-package: pojo
  mapper-locations: classpath:mapper/*.xml