server:
  address: 127.0.0.2
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QianNvYouHun
    url: jdbc:mysql://localhost:3306/zay_musicwebdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: musicDataBase
  servlet:
    multipart:
      max-file-size: 1020MB
      max-request-size: 1020MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2

mybatis:
  type-aliases-package: pojo
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql